[project]
name = "dbowser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["asyncpg>=0.29.0", "textual>=0.86.0"]

[project.scripts]
dbowser = "dbowser.main:main"
