[project]
name = "dbowser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.29.0",
    "pyte>=0.8.2",
    "textual>=0.86.0",
    "textual-vim>=0.1.0",
]

[project.scripts]
dbowser = "dbowser.main:main"
